version: '3.8'

services:
  email-automation:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - email-network

  # Optional: Add Redis for queue management
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - email-network

  # Optional: Add database
  # database:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: email_automation
  #     POSTGRES_USER: email_user
  #     POSTGRES_PASSWORD: email_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - email-network

networks:
  email-network:
    driver: bridge

# volumes:
#   postgres_data: